import '../models/product_model.dart';

final products = [
  ProductModel(
    imagePath: "assets/products/evening_dress.png",
    rating: 4.5,
    boughtCount: 10,
    category: "Dorothy Perkins",
    title: "Evening Dress",
    currentPrice: 12,
    oldPrice: 15,
  ),
  ProductModel(
    imagePath: "assets/products/sports_dress.png",
    rating: 4.2,
    boughtCount: 8,
    category: "Sitlly",
    title: "Sports Dress",
    currentPrice: 19,
    oldPrice: 22,
  ),
  ProductModel(
    imagePath: "assets/products/casual_shirt.webp",
    rating: 4.4,
    boughtCount: 20,
    category: "Zara",
    title: "Casual Shirt",
    currentPrice: 22,
  ),
  // ProductModel(
  //   imagePath: "assets/images/shoes1.png",
  //   rating: 4.7,
  //   boughtCount: 42,
  //   category: "Nike",
  //   title: "Air Max 90",
  //   currentPrice: 130,
  //   oldPrice: 150,
  // ),
  // ProductModel(
  //   imagePath: "assets/images/jeans1.png",
  //   rating: 4.3,
  //   boughtCount: 28,
  //   category: "Levi’s",
  //   title: "Slim Fit Jeans",
  //   currentPrice: 45,
  // ),
  // ProductModel(
  //   imagePath: "assets/images/tshirt1.png",
  //   rating: 4.2,
  //   boughtCount: 18,
  //   category: "Hollister",
  //   title: "Graphic T-Shirt",
  //   currentPrice: 18,
  //   oldPrice: 25,
  // ),
  // ProductModel(
  //   imagePath: "assets/images/skirt1.png",
  //   rating: 4.5,
  //   boughtCount: 14,
  //   category: "Forever 21",
  //   title: "Pleated Skirt",
  //   currentPrice: 28,
  // ),
  // ProductModel(
  //   imagePath: "assets/images/watch1.png",
  //   rating: 4.9,
  //   boughtCount: 50,
  //   category: "Fossil",
  //   title: "Classic Wristwatch",
  //   currentPrice: 160,
  //   oldPrice: 200,
  // ),
  // ProductModel(
  //   imagePath: "assets/images/bag1.png",
  //   rating: 4.6,
  //   boughtCount: 33,
  //   category: "Michael Kors",
  //   title: "Leather Handbag",
  //   currentPrice: 210,
  // ),
  // ProductModel(
  //   imagePath: "assets/images/hoodie1.png",
  //   rating: 4.7,
  //   boughtCount: 40,
  //   category: "Adidas",
  //   title: "Comfy Hoodie",
  //   currentPrice: 55,
  //   oldPrice: 70,
  // ),
];


